name: maxidoku
description: A new Flutter game that creates many kinds of Sudoku puzzle.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  community_material_icon:
  flutter:
    sdk: flutter

  audioplayers: ^1.0.1
  # cupertino_icons: ^1.0.2
  go_router: ^4.4.1
  logging: ^1.0.2


  flutter_localizations:
    sdk: flutter
  get_storage: ^2.0.3 # New version 2.1.1 avail Feb '23.
  provider: ^6.0.2
  shared_preferences: ^2.0.13 # NOT USED.

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  # firebase_core: ^1.15.0  # Needed for Crashlytics below
    # firebase_core: Using Firebase SDK version '9.6.0' defined in 'firebase_core'
    # [!] Failed to load 'firebase_core' podspec: 
    # [!] Invalid `firebase_core.podspec` file: [!] The FlutterFire plugin
    # firebase_core for macOS requires a macOS deployment target of 10.12 or
    # later..

  # firebase_crashlytics: ^2.8.1  # Error reporting

  # Flutter can't find compatible versions in Podfile...
  # games_services: ^3.0.0  # Achievements and leaderboards

  # google_mobile_ads: ^2.0.1  # Ads

  # Flutter can't find compatible versions in Podfile...
  # in_app_purchase: ^3.0.1  # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ??? flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  # ??? test: ^1.19.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    # Obsolete icons removed from repository - new ones needed.
    # - assets/images/hi64-action-ksudoku-ksudoku_9x9.png
    - assets/images/flutter_logo.png
    # Add assets from the MaxiDoku icons directory to the application.
    # - assets/icons/
