name: multidoku
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  community_material_icon:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  get_storage: ^2.0.3
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/hi64-action-ksudoku-ksudoku_9x9.png
    - assets/images/flutter_logo.png
    # Add assets from the MultiDoku icons directory to the application.
    - assets/icons/
